package com.smartgrid.strategy;

import com.smartgrid.model.CityZone;
import java.util.List;

/**
 * PATTERN 2: Strategy
 * The interface for different power distribution strategies.
 */
public interface DistributionStrategy {
    /**
     * Distributes the available power among the city zones.
     * @param totalAvailablePower The total power generated by the grid.
     * @param zones The list of city zones.
     */
    void distributePower(int totalAvailablePower, List<CityZone> zones);
    
    String getStrategyName();
}
